[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "UCI-SECOM-Semiconductor-Process-Data-Driven-Yield-Prediction-and-Guardband-Optimization"
version = "0.1.0"
description = "Semiconductor yield prediction using the SECOM dataset"
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]